build: Add dependencies among BUILT_SOURCES.
Without the change `make --shuffle` build fails occasionally as:

    $ make --shuffle
    ...
    make  all-recursive
    make[1]: Entering directory '/build/guile-reader'
    Making all in src
    make[2]: Entering directory '/build/guile-reader/src'
      GEN      token-reader-list.c
      GEN      token-readers.x
    token-readers.c:1146:10: fatal error: token-reader-lookup.c: No such file or directory
     1146 | #include "token-reader-lookup.c"
          |          ^~~~~~~~~~~~~~~~~~~~~~~

Here buidl fails because `token-readers.x` depends on auto-generated
`token-reader-lookup.c` file. The change adds these missing dependencies
among `BUILT_SOURCES`.

Before the change `make --shuffle` was failing almost every build.
After the change: TODO

* src/Makefile.am (token-readers.x, reader.x): New targets.

Signed-off-by: Ludovic Courtès <ludo@gnu.org>